services:

  backend:
    build: ./backend
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    networks:
      - mynetwork

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data: